#!/usr/bin/env bash
# Install nginx on a linux server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx
