#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
# display hours from 0 to 12 and minutes from 1 to 59
hour=0
while ((hour <= 12))
do
	minute=1
	echo "Hour: $hour"
	while ((minute <= 59))
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
